## this just needs to exist with correct env for rake asset:precompile to run
## during docker image build; other details should not matter
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
